#define w_date_boy_look_away	0	// 練習開始直後のよそ見
#define w_date_boy_beat	1	// (null)
#define w_date_boy_beat_T	2	// (null)
#define w_date_boy_kick	3	// (null)
#define w_date_boy_miss	4	// (null)
#define w_date_girl_beat	5	// (null)
#define w_date_girl_look	6	// (null)
#define w_date_girl_sad	7	// (null)
#define w_date_girl_smile	8	// 最後
#define w_date_ball_soccer	9	// (null)
#define w_date_ball_rugby	10	// ジャストミート時の角度にしておいて下さい
#define w_date_ball_basket	11	// (null)
#define w_date_ball_shadow	12	// (null)
#define w_date_bench	13	// (null)
