// <auto-generated>MinigameLoaderGenerator</auto-generated>

using Debug = UnityEngine.Debug;
using HeavenStudio.Games.Loaders;

namespace HeavenStudio
{
    static partial class Minigames
    {

        public static void LoadMinigames(EventCaller eventCaller)
        {

            Minigames.Minigame game;

            game = RvlBadmintonLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlBadmintonLoader failed!");
            }

            game = CtrBearLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrBearLoader failed!");
            }

            game = RvlBoardMeetingLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlBoardMeetingLoader failed!");
            }

            game = AgbBonOdoriLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbBonOdoriLoader failed!");
            }

            game = NtrFlickLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrFlickLoader failed!");
            }

            game = CtrCatchLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrCatchLoader failed!");
            }

            game = RvlBookLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlBookLoader failed!");
            }

            game = AgbClapLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbClapLoader failed!");
            }

            game = NtrCoinLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrCoinLoader failed!");
            }

            game = NtrCropLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrCropLoader failed!");
            }

            game = NtrDjLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrDjLoader failed!");
            }

            game = NtrDogNinjaLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrDogNinjaLoader failed!");
            }

            game = RvlDoubleDateLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlDoubleDateLoader failed!");
            }

            game = CtrDrummingLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrDrummingLoader failed!");
            }

            game = NtrIdolLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrIdolLoader failed!");
            }

            game = AgbFireworkLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbFireworkLoader failed!");
            }

            game = CtrFirstContact.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrFirstContact failed!");
            }

            game = RvlFlipperFlopLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlFlipperFlopLoader failed!");
            }

            game = RvlForkLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlForkLoader failed!");
            }

            game = NtrGleeClubLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrGleeClubLoader failed!");
            }

            game = RvlNewKarateLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlNewKarateLoader failed!");
            }

            game = CtrTeppanLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrTeppanLoader failed!");
            }

            game = RvlRocketLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlRocketLoader failed!");
            }

            game = NtrBackbeatLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrBackbeatLoader failed!");
            }

            game = AgbMannequinFactoryLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbMannequinFactoryLoader failed!");
            }

            game = RvlManzaiLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlManzaiLoader failed!");
            }

            game = AgbMarcherLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbMarcherLoader failed!");
            }

            game = PcoMeatLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoMeatLoader failed!");
            }

            game = RvlMonkeyWatchLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlMonkeyWatchLoader failed!");
            }

            game = AgbUpbeatLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbUpbeatLoader failed!");
            }

            game = ntrMunchyMonkLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader ntrMunchyMonkLoader failed!");
            }

            game = AgbNightWalkLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbNightWalkLoader failed!");
            }

            game = NtrOctopusMachineLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrOctopusMachineLoader failed!");
            }

            game = CtrPillowLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrPillowLoader failed!");
            }

            game = AgbQuizShowLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbQuizShowLoader failed!");
            }

            game = NtrPingpongLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrPingpongLoader failed!");
            }

            game = PcoSomenLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoSomenLoader failed!");
            }

            game = AgbRhythmTestGBALoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbRhythmTestGBALoader failed!");
            }

            game = AgbHairLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbHairLoader failed!");
            }

            game = RvlRingsideLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlRingsideLoader failed!");
            }

            game = NtrRockersLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrRockersLoader failed!");
            }

            game = NtrSamuraiLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrSamuraiLoader failed!");
            }

            game = RvlSeeSawLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlSeeSawLoader failed!");
            }

            game = NtrSlotMonsterLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrSlotMonsterLoader failed!");
            }

            game = AgbGhostLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbGhostLoader failed!");
            }

            game = AgbBatterLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbBatterLoader failed!");
            }

            game = AgbSpaceDanceLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbSpaceDanceLoader failed!");
            }

            game = NtrSoccerLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrSoccerLoader failed!");
            }

            game = NtrSplashdownLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrSplashdownLoader failed!");
            }

            game = CtrSumouLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrSumouLoader failed!");
            }

            game = RvlTambourineLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlTambourineLoader failed!");
            }

            game = AgbTapLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbTapLoader failed!");
            }

            game = RvlTapTroupeLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlTapTroupeLoader failed!");
            }

            game = NtrDazzlesLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrDazzlesLoader failed!");
            }

            game = AgbTossBoysLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbTossBoysLoader failed!");
            }

            game = TotemClimbLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader TotemClimbLoader failed!");
            }

            game = AgbTramLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbTramLoader failed!");
            }

            game = MobTrickLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader MobTrickLoader failed!");
            }

            game = NtrTunnelLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrTunnelLoader failed!");
            }

            game = AgbWaltzLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbWaltzLoader failed!");
            }

            game = RvlWorkingDoughLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlWorkingDoughLoader failed!");
            }

        }

    }
}
