// <auto-generated>MinigameLoaderGenerator</auto-generated>

using Debug = UnityEngine.Debug;
using HeavenStudio.Games.Loaders;

namespace HeavenStudio
{
    static partial class Minigames
    {

        public static void LoadMinigames(EventCaller eventCaller)
        {

            Minigames.Minigame game;

            game = PcoCanneryLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoCanneryLoader failed!");
            }

            game = PcoDressYourBestLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoDressYourBestLoader failed!");
            }

            game = PcoMeatLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoMeatLoader failed!");
            }

            game = PcoNailLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoNailLoader failed!");
            }

            game = PcoVenusLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoVenusLoader failed!");
            }

            game = PcoSomenLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoSomenLoader failed!");
            }

            game = TotemClimbLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader TotemClimbLoader failed!");
            }

            game = MobTrickLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader MobTrickLoader failed!");
            }

            game = PcoWaffleLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoWaffleLoader failed!");
            }

        }

    }
}
