// <auto-generated>MinigameLoaderGenerator</auto-generated>

using Debug = UnityEngine.Debug;
using HeavenStudio.Games.Loaders;

namespace HeavenStudio
{
    static partial class Minigames
    {

        public static void LoadMinigames(EventCaller eventCaller)
        {

            Minigames.Minigame game;

            Debug.Log("Running game loader RvlBadmintonLoader");
            game = RvlBadmintonLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlBadmintonLoader failed!");
            }

            Debug.Log("Running game loader CtrBearLoader");
            game = CtrBearLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrBearLoader failed!");
            }

            Debug.Log("Running game loader RvlBoardMeetingLoader");
            game = RvlBoardMeetingLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlBoardMeetingLoader failed!");
            }

            Debug.Log("Running game loader NtrFlickLoader");
            game = NtrFlickLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrFlickLoader failed!");
            }

            Debug.Log("Running game loader CtrCatchLoader");
            game = CtrCatchLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrCatchLoader failed!");
            }

            Debug.Log("Running game loader RvlBookLoader");
            game = RvlBookLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlBookLoader failed!");
            }

            Debug.Log("Running game loader AgbClapLoader");
            game = AgbClapLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbClapLoader failed!");
            }

            Debug.Log("Running game loader NtrCoinLoader");
            game = NtrCoinLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrCoinLoader failed!");
            }

            Debug.Log("Running game loader NtrCropLoader");
            game = NtrCropLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrCropLoader failed!");
            }

            Debug.Log("Running game loader NtrDjLoader");
            game = NtrDjLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrDjLoader failed!");
            }

            Debug.Log("Running game loader NtrDogNinjaLoader");
            game = NtrDogNinjaLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrDogNinjaLoader failed!");
            }

            Debug.Log("Running game loader RvlDoubleDateLoader");
            game = RvlDoubleDateLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlDoubleDateLoader failed!");
            }

            Debug.Log("Running game loader CtrDrummingLoader");
            game = CtrDrummingLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrDrummingLoader failed!");
            }

            Debug.Log("Running game loader NtrIdolLoader");
            game = NtrIdolLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrIdolLoader failed!");
            }

            Debug.Log("Running game loader AgbFireworkLoader");
            game = AgbFireworkLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbFireworkLoader failed!");
            }

            Debug.Log("Running game loader CtrFirstContact");
            game = CtrFirstContact.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrFirstContact failed!");
            }

            Debug.Log("Running game loader RvlFlipperFlopLoader");
            game = RvlFlipperFlopLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlFlipperFlopLoader failed!");
            }

            Debug.Log("Running game loader RvlForkLoader");
            game = RvlForkLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlForkLoader failed!");
            }

            Debug.Log("Running game loader NtrGleeClubLoader");
            game = NtrGleeClubLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrGleeClubLoader failed!");
            }

            Debug.Log("Running game loader RvlNewKarateLoader");
            game = RvlNewKarateLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlNewKarateLoader failed!");
            }

            Debug.Log("Running game loader CtrTeppanLoader");
            game = CtrTeppanLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrTeppanLoader failed!");
            }

            Debug.Log("Running game loader RvlRocketLoader");
            game = RvlRocketLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlRocketLoader failed!");
            }

            Debug.Log("Running game loader NtrBackbeatLoader");
            game = NtrBackbeatLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrBackbeatLoader failed!");
            }

            Debug.Log("Running game loader AgbMarcherLoader");
            game = AgbMarcherLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbMarcherLoader failed!");
            }

            Debug.Log("Running game loader PcoMeatLoader");
            game = PcoMeatLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoMeatLoader failed!");
            }

            Debug.Log("Running game loader AgbUpbeatLoader");
            game = AgbUpbeatLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbUpbeatLoader failed!");
            }

            Debug.Log("Running game loader ntrMunchyMonkLoader");
            game = ntrMunchyMonkLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader ntrMunchyMonkLoader failed!");
            }

            Debug.Log("Running game loader NtrOctopusMachineLoader");
            game = NtrOctopusMachineLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrOctopusMachineLoader failed!");
            }

            Debug.Log("Running game loader CtrPillowLoader");
            game = CtrPillowLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader CtrPillowLoader failed!");
            }

            Debug.Log("Running game loader AgbQuizShowLoader");
            game = AgbQuizShowLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbQuizShowLoader failed!");
            }

            Debug.Log("Running game loader NtrPingpongLoader");
            game = NtrPingpongLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrPingpongLoader failed!");
            }

            Debug.Log("Running game loader PcoSomenLoader");
            game = PcoSomenLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader PcoSomenLoader failed!");
            }

            Debug.Log("Running game loader AgbHairLoader");
            game = AgbHairLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbHairLoader failed!");
            }

            Debug.Log("Running game loader RvlRingsideLoader");
            game = RvlRingsideLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlRingsideLoader failed!");
            }

            Debug.Log("Running game loader NtrRockersLoader");
            game = NtrRockersLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrRockersLoader failed!");
            }

            Debug.Log("Running game loader NtrSamuraiLoader");
            game = NtrSamuraiLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrSamuraiLoader failed!");
            }

            Debug.Log("Running game loader RvlSeeSawLoader");
            game = RvlSeeSawLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlSeeSawLoader failed!");
            }

            Debug.Log("Running game loader AgbGhostLoader");
            game = AgbGhostLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbGhostLoader failed!");
            }

            Debug.Log("Running game loader AgbBatterLoader");
            game = AgbBatterLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbBatterLoader failed!");
            }

            Debug.Log("Running game loader AgbSpaceDanceLoader");
            game = AgbSpaceDanceLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbSpaceDanceLoader failed!");
            }

            Debug.Log("Running game loader NtrSoccerLoader");
            game = NtrSoccerLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrSoccerLoader failed!");
            }

            Debug.Log("Running game loader NtrSplashdownLoader");
            game = NtrSplashdownLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrSplashdownLoader failed!");
            }

            Debug.Log("Running game loader RvlTambourineLoader");
            game = RvlTambourineLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlTambourineLoader failed!");
            }

            Debug.Log("Running game loader AgbTapLoader");
            game = AgbTapLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbTapLoader failed!");
            }

            Debug.Log("Running game loader RvlTapTroupeLoader");
            game = RvlTapTroupeLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlTapTroupeLoader failed!");
            }

            Debug.Log("Running game loader NtrDazzlesLoader");
            game = NtrDazzlesLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrDazzlesLoader failed!");
            }

            Debug.Log("Running game loader AgbTossBoysLoader");
            game = AgbTossBoysLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbTossBoysLoader failed!");
            }

            Debug.Log("Running game loader TotemClimbLoader");
            game = TotemClimbLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader TotemClimbLoader failed!");
            }

            Debug.Log("Running game loader AgbTramLoader");
            game = AgbTramLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbTramLoader failed!");
            }

            Debug.Log("Running game loader MobTrickLoader");
            game = MobTrickLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader MobTrickLoader failed!");
            }

            Debug.Log("Running game loader NtrTunnelLoader");
            game = NtrTunnelLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader NtrTunnelLoader failed!");
            }

            Debug.Log("Running game loader AgbWaltzLoader");
            game = AgbWaltzLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader AgbWaltzLoader failed!");
            }

            Debug.Log("Running game loader RvlWorkingDoughLoader");
            game = RvlWorkingDoughLoader.AddGame(eventCaller);
            if (game != null)
            {
                eventCaller.minigames.Add(game.name, game);
            }
            else
            {
                Debug.LogWarning("Game loader RvlWorkingDoughLoader failed!");
            }

        }

    }
}
